
package vistas;

import controlador.Perdonabd;
import javax.swing.JOptionPane;
import modelo.Persona;
import utilidades.Utilidades;

public class formulario extends javax.swing.JFrame {
    
private Utilidades utilidades;
    private Perdonabd controladorPersona;
    /**
     * Creates new form formulario
     */
    public formulario() {
        
        initComponents();
        utilidades = new Utilidades();
        controladorPersona = new Perdonabd();
    }
    public void limpiar (){
        txtcedula.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtdireccion.setText("");
        txtcorreo.setText("");
        txttelefono.setText("");
        txtcedula.requestFocus();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        botonguardar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botontraer = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jTextField1.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 0, 0));
        jTextField1.setText("REGISTRO DE PERSONAS");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 102, 153));

        lblcedula.setBackground(new java.awt.Color(255, 153, 153));
        lblcedula.setText("Cédula");

        lblnombres.setText("Nombres");

        lblapellidos.setText("Apellidos");

        lbldireccion.setText("Dirección");

        lblcorreo.setText("Correo");

        lbltelefono.setText("Teléfono");

        txtcedula.setBackground(new java.awt.Color(204, 204, 255));

        txtnombre.setBackground(new java.awt.Color(204, 204, 255));

        txtapellido.setBackground(new java.awt.Color(204, 204, 255));

        txtdireccion.setBackground(new java.awt.Color(204, 204, 255));

        txtcorreo.setBackground(new java.awt.Color(204, 204, 255));

        txttelefono.setBackground(new java.awt.Color(204, 204, 255));

        botonguardar.setBackground(new java.awt.Color(102, 102, 255));
        botonguardar.setForeground(new java.awt.Color(0, 0, 255));
        botonguardar.setText("Guardar");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });

        botoneliminar.setBackground(new java.awt.Color(255, 102, 102));
        botoneliminar.setForeground(new java.awt.Color(255, 0, 0));
        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });

        botontraer.setText("Traer");

        botonmodificar.setBackground(new java.awt.Color(153, 255, 153));
        botonmodificar.setForeground(new java.awt.Color(0, 153, 0));
        botonmodificar.setText("Modificar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldireccion)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblcorreo)
                                        .addComponent(lbltelefono))
                                    .addComponent(lblapellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblcedula)
                                        .addComponent(lblnombres)))
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botonguardar)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(botoneliminar)
                                .addGap(35, 35, 35)
                                .addComponent(botontraer)
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcedula)
                                    .addComponent(txtnombre)
                                    .addComponent(txtapellido)
                                    .addComponent(txtdireccion)
                                    .addComponent(txtcorreo)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonmodificar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedula)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonmodificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombres)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellidos)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcorreo)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonguardar)
                    .addComponent(botoneliminar)
                    .addComponent(botontraer))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
// TODO agregue su código de manejo aquí:
        if (txtcedula . getText () . isEmpty ()) {
            JOptionPane . showMessageDialog (rootPane, " El campo cedula no tiene datos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txtcedula . requestFocus (); // Sirve para ubicar el cursor en un campo vacio.
            return ;
        }
        if ( ! utilidades . validadorDeCedula (txtcedula . getText ())) {
            JOptionPane . showMessageDialog (rootPane, " la cedula ingresada no es valida " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            return ;
        }
        if (txtnombre . getText () . isEmpty ()) {
            JOptionPane . showMessageDialog (rootPane, " El campo nombres no tiene datos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txtnombre . requestFocus ();
            return ;
        } if (txtapellido . getText () . isEmpty ()) {
            JOptionPane . showMessageDialog (rootPane, " El campo apellidos no tiene datos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txtapellido . requestFocus ();
            return ;
        }
        if (txtdireccion . getText () . isEmpty ()) {
            JOptionPane . showMessageDialog (rootPane, " El campo direccion no tiene datos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txtdireccion . requestFocus ();
            return;
        }
        if (txttelefono . getText () . isEmpty ()) {
            JOptionPane . showMessageDialog (rootPane, " El campo telefono no tiene datos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txttelefono . requestFocus ();
            return ;
        }
        if ( ! utilidades . validarNumeros (txttelefono . getText ())) {
            JOptionPane . showMessageDialog (rootPane, " Los datos ingresados ​​en el teléfono no son validos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txttelefono . requestFocus ();
            return ;
        
        }
        if (txtcorreo . getText () . isEmpty ()) {
            JOptionPane . showMessageDialog (rootPane, " El campo correo no tiene datos. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txtcorreo . requestFocus ();
            return ;
        }
        if ( ! utilidades . validarcorreo (txtcorreo . getText ())) {
            JOptionPane . showMessageDialog (rootPane, " El correo ingresado no es correcto. " , " ERROR " , JOptionPane . ERROR_MESSAGE );
            txtcorreo . requestFocus ();
            return ;
        }
        Persona persona = new Persona();
        persona.setCedula(txtcedula.getText());
        persona.setNombre(txtnombre.getText());
        persona.setApellidos(txtapellido.getText());
        persona.setDireccion(txtdireccion.getText());
        persona.setCorreo(txtcorreo.getText());
        persona.setTelefono(txttelefono.getText());
        System.out.println(persona.toString());
        if (controladorPersona.registrarPersona(persona)) {
            JOptionPane.showMessageDialog(rootPane, "Persona registrada en el sistema.");
            limpiar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se puede guardar la persona","ERROR",JOptionPane.ERROR_MESSAGE);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_botonguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JButton botontraer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
